platform :ios, '13.1'

target 'Flash Chat iOS13' do
  use_frameworks!

  # Pods for Flash Chat iOS13
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseCore'
pod 'FirebaseStorage'

end
